on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (CS)"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["stable", "current"]
        include:
          - racket-version: current
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - uses: Bogdanp/setup-racket@v1.12
        with:
          architecture: x64
          distribution: full
          variant: CS
          version: ${{ matrix.racket-version }}
      - name: Installing ai-rangler and its dependencies
        run: raco pkg install --no-docs --auto --name ai-rangler
      - name: Compiling ai-rangler and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps ai-rangler
      - name: Testing ai-rangler
        run: raco test -x -p ai-rangler
